name: Deploy

on:
  workflow_call:
    inputs:
      forRef:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      forRef:
        description: 'Branch, SHA or Tag to release'
        required: false
        type: string

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  generate-artifacts:
    name: Generate artifacts
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.forRef }}

    - name: Unshallow
      run: git fetch --prune --unshallow

    - name: Ensure release-notes exists
      run: touch /tmp/release-notes.md

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libdevmapper-dev libbtrfs-dev

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        check-latest: true
        cache: true

    - name: Login to github registry
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4.4.0
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
